"""
OrangeTree Global — AI Reservation Chat Agent (UC10)
Powered by Claude API (Anthropic)
Run: streamlit run uc10_reservation_agent.py
"""

import streamlit as st
import anthropic
import json
from datetime import datetime

LOGO_B64 = "PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjUgOSAxNTg2IDI2OCIgd2lkdGg9IjE1ODYiIGhlaWdodD0iMjY4Ij48dGl0bGU+T3JhbmdlVHJlZS57YWl9PC90aXRsZT48cGF0aCBmaWxsPSIjMUE3QTMwIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiIGQ9Ik0xODIuNSAxM0wxODMuNSAxM0wxODMuNSAxOEwxODIuNSAxOUwxODIuNSAyMkwxODEuNSAyM0wxODAuNSAyOEwxNzguNSAzMUwxNzguNSAzM0wxNzMuNSA0M0wxNzEuNSA0NUwxNjcuNSA1MkwxNjMuNSA1NkwxNjMuNSA1N0wxNTMgNjcuNUwxNTIgNjcuNUwxNDUgNzMuNUwxNDIgNzQuNUwxNDAgNzYuNUwxMzYgNzguNUwxMzQgNzguNUwxMzAgODAuNUwxMjcgODAuNUwxMjYgODEuNUwxMTYgODEuNUwxMTUgODAuNUwxMTIgODAuNUwxMDUgNzYuNUwxMDAuNSA3MkwxMDAuNSA3MUwxMDYgNjguNUwxMDggNjYuNUwxMTUgNjIuNUwxMTggNTkuNUwxMTkgNTkuNUwxMjQgNTQuNUwxMjUgNTQuNUwxMzEuNSA0OEwxMzEuNSA0N0wxMzAgNDYuNUwxMTUgNTQuNUwxMTMgNTQuNUwxMDkgNTYuNUwxMDYgNTYuNUwxMDUgNTcuNUw5NiA1Ny41TDk1IDU2LjVMOTMgNTYuNUw4OC41IDUxTDg4LjUgNDRMOTIuNSAzNUw5NS41IDMyTDk1LjUgMzFMMTAzIDI0LjVMMTEyIDIwLjVMMTE5IDIwLjVMMTIwIDE5LjVMMTQ4IDE5LjVMMTQ5IDE4LjVMMTU5IDE4LjVMMTYwIDE3LjVMMTY2IDE3LjVMMTY3IDE2LjVMMTcxIDE2LjVMMTcyIDE1LjVMMTc1IDE1LjVMMTc2IDE0LjVMMTgyIDEzLjVaTTI5LjUgMTdMMzAgMTYuNUwzNCAyMC41TDM1IDIwLjVMNDAgMjQuNUw1MiAzMC41TDU0IDMwLjVMNjMgMzUuNUw2NSAzNS41TDY3IDM3LjVMNzIgMzkuNUw3NSA0Mi41TDc2IDQyLjVMODIuNSA1MEw4Mi41IDUyTDg0LjUgNTZMODQuNSA2MEw4MyA2MS41TDc3IDYyLjVMNzYgNjMuNUw2OCA2My41TDY3IDY0LjVMNjYgNjMuNUw1OSA2My41TDU4IDYyLjVMNTUgNjIuNUw0NiA1Ny41TDM4LjUgNDlMMzQuNSA0MUwzMy41IDM1TDMyLjUgMzRMMzIuNSAzMUwzMS41IDMwTDMxLjUgMjRMMzAuNSAyM0wzMCAxNy41Wk0xMzEuNSA0NkwxMzIgNDUuNUwxMzIgNDYuNVoiPjwvcGF0aD48cGF0aCBmaWxsPSIjRjM2NjIxIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiIGQ9Ik05My41IDg3TDExOSA4Ni41TDEyMCA4Ny41TDEyNCA4Ny41TDEyNSA4OC41TDEzMyA5MC41TDE0MyA5NS41TDE0NSA5Ny41TDE1MiAxMDEuNUwxNTYgMTA1LjVMMTU3IDEwNS41TDE2Ni41IDExNUwxNjYuNSAxMTZMMTcwLjUgMTIwTDE3MC41IDEyMUwxNzMuNSAxMjRMMTc0LjUgMTI3TDE3Ni41IDEyOUwxODEuNSAxMzlMMTgxLjUgMTQxTDE4Mi41IDE0MkwxODIuNSAxNDRMMTg1LjUgMTUxTDE4NS41IDE1NEwxODYuNSAxNTVMMTg2LjUgMTYwTDE4Ny41IDE2MUwxODcuNSAxODFMMTg2LjUgMTgyTDE4Ni41IDE4OEwxODUuNSAxODlMMTg1LjUgMTkzTDE4My41IDE5N0wxODIuNSAyMDNMMTc5LjUgMjA4TDE3OS41IDIxMEwxNzcuNSAyMTRMMTc1LjUgMjE2TDE3NC41IDIxOUwxNjcuNSAyMjhMMTY3LjUgMjI5TDE1NSAyNDEuNUwxNTQgMjQxLjVMMTUxIDI0NC41TDE1MCAyNDQuNUwxNDUgMjQ4LjVMMTQyIDI0OS41TDE0MCAyNTEuNUwxMzYgMjUzLjVMMTM0IDI1My41TDEyOSAyNTYuNUwxMjMgMjU3LjVMMTE5IDI1OS41TDExNSAyNTkuNUwxMTQgMjYwLjVMMTA4IDI2MC41TDEwNyAyNjEuNUw4OSAyNjEuNUw4OCAyNjAuNUw4MiAyNjAuNUw4MSAyNTkuNUw3MyAyNTguNUw3MiAyNTcuNUw2NyAyNTYuNUw2NCAyNTQuNUw2MiAyNTQuNUw1MiAyNDkuNUw0MyAyNDIuNUw0MiAyNDIuNUwyNi41IDIyN0wyNi41IDIyNkwyMC41IDIxOEwxMi41IDIwMUwxMS41IDE5NUwxMC41IDE5NEwxMC41IDE5MUw5LjUgMTkwTDkuNSAxODVMOC41IDE4NEw4LjUgMTYyTDkuNSAxNjFMMTAuNSAxNTNMMTEuNSAxNTJMMTMuNSAxNDRMMTYuNSAxMzhMMTguNSAxMzZMMjEuNSAxMzBMMzEgMTE5LjVMMzEuNSAxMjBMMjQuNSAxMzNMMjQuNSAxMzVMMjEuNSAxNDJMMjEuNSAxNTVMMjQuNSAxNjFMMzAgMTY1LjVMMzYgMTY4LjVMNDQgMTY5LjVMNDUgMTcwLjVMNzEgMTcwLjVMNzIgMTY5LjVMNzYgMTY5LjVMNzcgMTY4LjVMODAgMTY4LjVMODEgMTY3LjVMODkgMTY1LjVMMTA1IDE1Ny41TDEwNyAxNTUuNUwxMTQgMTUxLjVMMTMxLjUgMTM1TDEzMS41IDEzNEwxMzYuNSAxMjhMMTQwLjUgMTE5TDE0MC41IDEwOUwxMzguNSAxMDVMMTMyIDk4LjVMMTI0IDk0LjVMMTIwIDk0LjVMMTE5IDkzLjVMMTA0IDkzLjVMMTAzIDk0LjVMOTUgOTUuNUw5NCA5Ni41TDg5IDk3LjVMODQgMTAwLjVMODIgMTAwLjVMODAgMTAyLjVMNzcgMTAzLjVMNzEgMTA4LjVMNzAgMTA4LjVMNjAuNSAxMThMNjAuNSAxMTlMNTcuNSAxMjJMNTYuNSAxMjVMNTQuNSAxMjdMNTQuNSAxMjlMNTIuNSAxMzNMNTIuNSAxNDFMNTQuNSAxNDVMNTcgMTQ3LjVMNjMgMTUwLjVMNzQgMTUwLjVMNzUgMTQ5LjVMNzkgMTQ4LjVMODQuNSAxNDNMODUuNSAxNDFMODUuNSAxMzNMODQuNSAxMzJMODMuNSAxMjdMNzcuNSAxMTlMODUgMTE0LjVMODcgMTE0LjVMOTMgMTExLjVMOTYgMTExLjVMOTcgMTEwLjVMMTExIDExMC41TDExNy41IDExNkwxMTcuNSAxMThMMTE4LjUgMTE5TDExOC41IDEyNEwxMTcuNSAxMjVMMTE3LjUgMTI4TDExMi41IDEzN0wxMDMgMTQ2LjVMOTAgMTU0LjVMODggMTU0LjVMODUgMTU2LjVMODMgMTU2LjVMNzkgMTU4LjVMNzYgMTU4LjVMNzUgMTU5LjVMNzAgMTU5LjVMNjkgMTYwLjVMNTMgMTYwLjVMNTIgMTU5LjVMNDggMTU5LjVMNDcgMTU4LjVMNDIgMTU3LjVMMzUgMTUzLjVMMzAuNSAxNDhMMzAuNSAxNDZMMjguNSAxNDJMMjguNSAxMzZMMjkuNSAxMzVMMjkuNSAxMzFMMzQuNSAxMjFMMzcuNSAxMThMMzcuNSAxMTdMNDcgMTA3LjVMNDggMTA3LjVMNTIgMTAzLjVMNTMgMTAzLjVMNTggOTkuNUw3MiA5Mi41TDc0IDkyLjVMNzUgOTEuNUw3NyA5MS41TDg0IDg4LjVMODcgODguNUw4OCA4Ny41TDkzIDg3LjVaIj48L3BhdGg+PHBhdGggZmlsbD0iIzAwMDAwMCIgZmlsbC1ydWxlPSJldmVub2RkIiBkPSJNMjcwLjUgNzFMMjc3IDcwLjVMMjc4IDcxLjVMMjg3IDcxLjVMMjg4IDcyLjVMMjkyIDcyLjVMMjk2IDc0LjVMMjk5IDc0LjVMMzAyIDc2LjVMMzA0IDc2LjVMMzEwIDc5LjVMMzE5IDg2LjVMMzIwIDg2LjVMMzI4LjUgOTVMMzI4LjUgOTZMMzMzLjUgMTAyTDMzNC41IDEwNUwzMzYuNSAxMDdMMzM5LjUgMTEzTDMzOS41IDExNUwzNDEuNSAxMThMMzQyLjUgMTI0TDM0NC41IDEyOEwzNDUuNSAxMzhMMzQ2LjUgMTM5TDM0Ni41IDE2OEwzNDUuNSAxNjlMMzQ0LjUgMTc5TDM0My41IDE4MEwzNDMuNSAxODNMMzQyLjUgMTg0TDM0MC41IDE5MkwzMzguNSAxOTVMMzM4LjUgMTk3TDMzNi41IDIwMUwzMzQuNSAyMDNMMzMzLjUgMjA2TDMyOC41IDIxMkwzMjguNSAyMTNMMzE1IDIyNS41TDMxNCAyMjUuNUwzMDkgMjI5LjVMMzAzIDIzMi41TDMwMSAyMzIuNUwyOTggMjM0LjVMMjkyIDIzNS41TDI5MSAyMzYuNUwyODggMjM2LjVMMjg3IDIzNy41TDI4MSAyMzcuNUwyODAgMjM4LjVMMjYzIDIzOC41TDI2MiAyMzcuNUwyNTcgMjM3LjVMMjU2IDIzNi41TDI0OSAyMzUuNUwyNDEgMjMxLjVMMjM5IDIzMS41TDIzNyAyMjkuNUwyMzQgMjI4LjVMMjMyIDIyNi41TDIyOCAyMjQuNUwyMTMuNSAyMDlMMjEwLjUgMjAzTDIwOC41IDIwMUwyMDcuNSAxOTdMMjA0LjUgMTkyTDIwNC41IDE5MEwyMDIuNSAxODZMMjAyLjUgMTgzTDIwMS41IDE4MkwyMDEuNSAxNzlMMjAwLjUgMTc4TDIwMC41IDE3M0wxOTkuNSAxNzJMMTk4LjUgMTUwTDE5OS41IDE0OUwxOTkuNSAxNDBMMjAwLjUgMTM5TDIwMC41IDEzNEwyMDEuNSAxMzNMMjAyLjUgMTI2TDIwMy41IDEyNUwyMDQuNSAxMjBMMjA2LjUgMTE3TDIwNi41IDExNUwyMTAuNSAxMDdMMjEyLjUgMTA1TDIxNi41IDk4TDIyOSA4NS41TDIzMCA4NS41TDIzOCA3OS41TDI0MiA3Ny41TDI0NCA3Ny41TDI0NyA3NS41TDI1MiA3NC41TDI1MyA3My41TDI2MSA3Mi41TDI2MiA3MS41TDI3MCA3MS41Wk0xMjgyLjUgNzFMMTI5MC41IDcxTDEyOTAuNSA4NEwxMjgwIDg0LjVMMTI3OSA4NS41TDEyNzcgODUuNUwxMjcwLjUgOTFMMTI2OC41IDk1TDEyNjguNSA5N0wxMjY3LjUgOThMMTI2Ny41IDExNEwxMjY4LjUgMTE1TDEyNjguNSAxMjFMMTI2OS41IDEyMkwxMjY5LjUgMTI4TDEyNzAuNSAxMjlMMTI3MC41IDE0OUwxMjY5LjUgMTUwTDEyNjguNSAxNTVMMTI2Ni41IDE1N0wxMjY2LjUgMTU4TDEyNjEgMTYzLjVMMTI1NyAxNjUuNUwxMjU1IDE2NS41TDEyNTQuNSAxNjdMMTI2MSAxNjkuNUwxMjY2LjUgMTc1TDEyNjkuNSAxODFMMTI2OS41IDE4NEwxMjcwLjUgMTg1TDEyNzAuNSAyMDVMMTI2OS41IDIwNkwxMjY4LjUgMjE5TDEyNjcuNSAyMjBMMTI2Ny41IDIzNUwxMjY4LjUgMjM2TDEyNjguNSAyMzlMMTI3MC41IDI0M0wxMjc0IDI0Ni41TDEyODEgMjQ5LjVMMTI5MC41IDI1MEwxMjkwLjUgMjYyTDEyNzYgMjYyLjVMMTI3NSAyNjEuNUwxMjY5IDI2MC41TDEyNjMgMjU3LjVMMTI1NS41IDI1MEwxMjUyLjUgMjQ0TDEyNTIuNSAyNDJMMTI1MS41IDI0MUwxMjUxLjUgMjM2TDEyNTAuNSAyMzVMMTI1MS41IDIxNUwxMjUyLjUgMjE0TDEyNTIuNSAyMDhMMTI1My41IDIwN0wxMjUzLjUgMjAxTDEyNTQuNSAyMDBMMTI1NC41IDE4NUwxMjUzLjUgMTg0TDEyNTIuNSAxODBMMTI0OCAxNzUuNUwxMjQ0IDE3NC41TDEyNDMgMTczLjVMMTIzOSAxNzMuNUwxMjM1LjUgMTcyTDEyMzUuNSAxNjFMMTI0NCAxNTkuNUwxMjUwIDE1Ni41TDEyNTEuNSAxNTVMMTI1NC41IDE0OEwxMjU0LjUgMTMzTDEyNTMuNSAxMzJMMTI1My41IDEyNUwxMjUyLjUgMTI0TDEyNTEuNSAxMTBMMTI1MC41IDEwOUwxMjUwLjUgOThMMTI1MS41IDk3TDEyNTIuNSA4OUwxMjU2LjUgODJMMTI2NCA3NS41TDEyNzEgNzIuNUwxMjc0IDcyLjVMMTI3NSA3MS41TDEyODIgNzEuNVpNMTQyMC41IDcxTDE0MjggNzAuNUwxNDI5IDcxLjVMMTQzNiA3MS41TDE0MzcgNzIuNUwxNDQzIDczLjVMMTQ1MCA3Ny41TDE0NTUuNSA4M0wxNDU4LjUgODlMMTQ1OS41IDk1TDE0NjAuNSA5NkwxNDYwLjUgMTEyTDE0NTkuNSAxMTNMMTQ1OS41IDEyMEwxNDU4LjUgMTIxTDE0NTcuNSAxMzZMMTQ1Ni41IDEzN0wxNDU2LjUgMTQ2TDE0NTcuNSAxNDdMMTQ1Ny41IDE1MUwxNDYzIDE1Ny41TDE0NjcgMTU5LjVMMTQ3Ni41IDE2MUwxNDc2LjUgMTcyTDE0NzMgMTcyLjVMMTQ3MiAxNzMuNUwxNDY4IDE3My41TDE0NjIgMTc2LjVMMTQ1OC41IDE4MUwxNDU3LjUgMTgzTDE0NTcuNSAxODZMMTQ1Ni41IDE4N0wxNDU3LjUgMjA1TDE0NTguNSAyMDZMMTQ1OS41IDIyMEwxNDYwLjUgMjIxTDE0NjAuNSAyMzdMMTQ1OS41IDIzOEwxNDU5LjUgMjQyTDE0NTYuNSAyNDlMMTQ1MSAyNTUuNUwxNDUwIDI1NS41TDE0NDUgMjU5LjVMMTQ0MyAyNTkuNUwxNDM5IDI2MS41TDE0MzYgMjYxLjVMMTQzNSAyNjIuNUwxNDIwLjUgMjYyTDE0MjAuNSAyNTBMMTQzMCAyNDkuNUwxNDMxIDI0OC41TDE0MzMgMjQ4LjVMMTQzNyAyNDYuNUwxNDQwLjUgMjQzTDE0NDIuNSAyMzlMMTQ0Mi41IDIzN0wxNDQzLjUgMjM2TDE0NDMuNSAyMThMMTQ0Mi41IDIxN0wxNDQyLjUgMjEwTDE0NDEuNSAyMDlMMTQ0MS41IDIwNEwxNDQwLjUgMjAzTDE0NDAuNSAxODZMMTQ0MS41IDE4NUwxNDQyLjUgMTc5TDE0NDUuNSAxNzRMMTQ1MiAxNjguNUwxNDU2LjUgMTY3TDE0NTYgMTY1LjVMMTQ1MiAxNjQuNUwxNDQ1LjUgMTU5TDE0NDIuNSAxNTRMMTQ0Mi41IDE1MkwxNDQwLjUgMTQ4TDE0NDAuNSAxMzFMMTQ0MS41IDEzMEwxNDQxLjUgMTI0TDE0NDIuNSAxMjNMMTQ0Mi41IDExN0wxNDQzLjUgMTE2TDE0NDMuNSA5N0wxNDQyLjUgOTZMMTQ0Mi41IDk0TDE0NDEuNSA5MkwxNDM2IDg2LjVMMTQzNCA4NS41TDE0MzIgODUuNUwxNDMxIDg0LjVMMTQyMSA4NC41TDE0MjAuNSA3MlpNMTU4NC41IDczTDE1ODcuNSA3M0wxNTg3IDkxLjVMMTU4Ni41IDgzTDE1ODUuNSA4MkwxNTg1LjUgNzZMMTU4NC41IDc0Wk04MjkuNSA3NEw5NDkuNSA3NEw5NDkgOTEuNUw5MDAuNSA5Mkw5MDAgMjM1LjVMODc5LjUgMjM1TDg3OS41IDkyTDgzMCA5MS41TDgyOS41IDc1Wk0xNDAwLjUgNzRMMTQwOCA3My41TDE0MDkgNzQuNUwxNDExIDc0LjVMMTQxNi41IDgwTDE0MTYuNSA4MkwxNDE3LjUgODNMMTQxNy41IDkxTDE0MTYuNSA5M0wxNDExIDk4LjVMMTQwOSA5OC41TDE0MDggOTkuNUwxNDAxIDk5LjVMMTQwMCA5OC41TDEzOTggOTguNUwxMzkyLjUgOTNMMTM5Mi41IDkxTDEzOTEuNSA5MEwxMzkxLjUgODNMMTM5Mi41IDgyTDEzOTIuNSA4MEwxMzk4IDc0LjVMMTQwMCA3NC41Wk0yNjMuNSA4OUwyODIgODguNUwyODMgODkuNUwyODYgODkuNUwyODcgOTAuNUwyODkgOTAuNUwyOTYgOTMuNUwzMDIgOTguNUwzMDMgOTguNUwzMDguNSAxMDRMMzA4LjUgMTA1TDMxNS41IDExNEwzMTguNSAxMjBMMzE4LjUgMTIyTDMxOS41IDEyM0wzMTkuNSAxMjVMMzIyLjUgMTMyTDMyMy41IDE0MkwzMjQuNSAxNDNMMzI0LjUgMTY2TDMyMy41IDE2N0wzMjMuNSAxNzJMMzIyLjUgMTczTDMyMi41IDE3N0wzMjEuNSAxNzhMMzIwLjUgMTg0TDMxOC41IDE4N0wzMTguNSAxODlMMzE0LjUgMTk3TDMxMi41IDE5OUwzMTAuNSAyMDNMMzAxIDIxMi41TDI5MyAyMTcuNUwyOTEgMjE3LjVMMjg4IDIxOS41TDI4NSAyMTkuNUwyODQgMjIwLjVMMjgwIDIyMC41TDI3OSAyMjEuNUwyNjcgMjIxLjVMMjY2IDIyMC41TDI2MiAyMjAuNUwyNjEgMjE5LjVMMjU4IDIxOS41TDI1NSAyMTcuNUwyNTMgMjE3LjVMMjQ1IDIxMi41TDIzNS41IDIwM0wyMjYuNSAxODdMMjI2LjUgMTg1TDIyNC41IDE4MUwyMjQuNSAxNzhMMjIzLjUgMTc3TDIyMy41IDE3NEwyMjIuNSAxNzNMMjIyLjUgMTY4TDIyMS41IDE2N0wyMjEuNSAxNDRMMjIyLjUgMTQzTDIyMi41IDEzN0wyMjMuNSAxMzZMMjIzLjUgMTMzTDIyNC41IDEzMkwyMjQuNSAxMjlMMjI1LjUgMTI4TDIyNy41IDEyMEwyMzMuNSAxMDlMMjQ0IDk3LjVMMjU0IDkxLjVMMjU2IDkxLjVMMjYwIDg5LjVMMjYzIDg5LjVaTTQwMi41IDExN0w0MTAgMTE2LjVMNDEyLjUgMTE4TDQxMi41IDEzN0w0MTEgMTM3LjVMNDEwIDEzNi41TDQwMiAxMzYuNUw0MDEgMTM3LjVMMzk4IDEzNy41TDM5MSAxNDAuNUwzODEuNSAxNTFMMzc5LjUgMTU1TDM3OC41IDE2MEwzNzcuNSAxNjFMMzc3LjUgMTY0TDM3Ni41IDE2NUwzNzYuNSAyMzVMMzU1LjUgMjM1TDM1NS41IDEzNUwzNTQuNSAxMzRMMzU0LjUgMTIwTDM3Mi41IDEyMEwzNzIuNSAxMjVMMzczLjUgMTI2TDM3NCAxNDIuNUwzODAuNSAxMzBMMzg4IDEyMi41TDM5NSAxMTguNUwzOTcgMTE4LjVMMzk4IDExNy41TDQwMiAxMTcuNVpNNDQ2LjUgMTE3TDQ2MCAxMTYuNUw0NjEgMTE3LjVMNDY2IDExNy41TDQ2NyAxMTguNUw0NzMgMTE5LjVMNDc5IDEyMi41TDQ4OC41IDEzMUw0OTQuNSAxNDJMNDk1LjUgMTQ4TDQ5Ni41IDE0OUw0OTYuNSAxNTRMNDk3LjUgMTU1TDQ5Ny41IDIyM0w0OTguNSAyMjRMNDk4LjUgMjMzTDQ5OS41IDIzNUw0ODEgMjM1LjVMNDc5LjUgMjM0TDQ3OS41IDIyNkw0NzguNSAyMjVMNDc4IDIyMS41TDQ2OSAyMzAuNUw0NjAgMjM1LjVMNDU4IDIzNS41TDQ1NCAyMzcuNUw0NTAgMjM3LjVMNDQ5IDIzOC41TDQzNiAyMzguNUw0MzUgMjM3LjVMNDMxIDIzNy41TDQzMCAyMzYuNUw0MjggMjM2LjVMNDE5IDIzMS41TDQxMy41IDIyNkw0MDguNSAyMTdMNDA3LjUgMjExTDQwNi41IDIxMEw0MDYuNSAyMDBMNDA3LjUgMTk5TDQwNy41IDE5NUw0MDguNSAxOTRMNDEwLjUgMTg3TDQxMi41IDE4NUw0MTQuNSAxODFMNDE5IDE3Ni41TDQyMCAxNzYuNUw0MjYgMTcxLjVMNDMyIDE2OC41TDQzNCAxNjguNUw0MzcgMTY2LjVMNDQwIDE2Ni41TDQ0NCAxNjQuNUw0NTQgMTYzLjVMNDU1IDE2Mi41TDQ2NCAxNjIuNUw0NjUgMTYxLjVMNDc2LjUgMTYxTDQ3Ni41IDE1Mkw0NzUuNSAxNTFMNDc1LjUgMTQ4TDQ3Mi41IDE0Mkw0NjcgMTM2LjVMNDYxIDEzMy41TDQ1OCAxMzMuNUw0NTcgMTMyLjVMNDQyIDEzMi41TDQ0MSAxMzMuNUw0MzcgMTMzLjVMNDM2IDEzNC41TDQyOCAxMzYuNUw0MjEgMTQwLjVMNDE5LjUgMTQwTDQxNy41IDEzM0w0MTYuNSAxMzJMNDE2LjUgMTMwTDQxNS41IDEyOUw0MTUuNSAxMjdMNDE3IDEyNS41TDQzMSAxMTkuNUw0MzQgMTE5LjVMNDM1IDExOC41TDQzOCAxMTguNUw0MzkgMTE3LjVMNDQ2IDExNy41Wk01NjUuNSAxMTdMNTc2IDExNi41TDU3NyAxMTcuNUw1ODIgMTE3LjVMNTg4IDEyMC41TDU5MCAxMjAuNUw1OTIgMTIyLjVMNTk1IDEyMy41TDYwMy41IDEzMkw2MDkuNSAxNDNMNjA5LjUgMTQ2TDYxMS41IDE1MEw2MTEuNSAxNTVMNjEyLjUgMTU2TDYxMi41IDIzNUw1OTEuNSAyMzVMNTkxLjUgMTYyTDU5MC41IDE2MUw1OTAuNSAxNTZMNTg5LjUgMTU1TDU4OS41IDE1Mkw1ODUuNSAxNDRMNTc3IDEzNi41TDU3NSAxMzYuNUw1NzEgMTM0LjVMNTU5IDEzNC41TDU1OCAxMzUuNUw1NTUgMTM1LjVMNTQ5IDEzOC41TDUzOS41IDE0OEw1MzYuNSAxNTRMNTM2LjUgMTU2TDUzNS41IDE1N0w1MzUuNSAxNjJMNTM0LjUgMTYzTDUzNC41IDIzNUw1MTMuNSAyMzVMNTEzLjUgMTI1TDUxMi41IDEyNEw1MTIuNSAxMjBMNTMxIDExOS41TDUzMyAxMzguNUw1MzUuNSAxMzRMNTQ1IDEyNC41TDU0NiAxMjQuNUw1NDggMTIyLjVMNTU3IDExOC41TDU2NSAxMTcuNVpNNjY3LjUgMTE3TDY3OCAxMTYuNUw2NzkgMTE3LjVMNjg0IDExNy41TDY4NSAxMTguNUw2ODggMTE4LjVMNjk4IDEyMy41TDcwNi41IDEzMkw3MDkgMTM2LjVMNzA5LjUgMTMwTDcxMC41IDEyOUw3MTEgMTE5LjVMNzI5LjUgMTIwTDcyOS41IDEyM0w3MjguNSAxMjRMNzI4LjUgMjI4TDcyNy41IDIyOUw3MjcuNSAyMzlMNzI2LjUgMjQwTDcyNS41IDI0OUw3MjQuNSAyNTBMNzIzLjUgMjU1TDcxNy41IDI2Nkw3MDggMjc1LjVMNzA2IDI3Ni41TDYzMC41IDI3Nkw2MzEuNSAyNzVMNjMxLjUgMjczTDYzMi41IDI3Mkw2MzIuNSAyNzBMNjMzLjUgMjY5TDYzMy41IDI2N0w2MzQuNSAyNjZMNjM2IDI2MC41TDY0MyAyNjQuNUw2NDUgMjY0LjVMNjUyIDI2Ny41TDY1NSAyNjcuNUw2NTYgMjY4LjVMNjYxIDI2OC41TDY2MiAyNjkuNUw2NzcgMjY5LjVMNjc4IDI2OC41TDY4MiAyNjguNUw2ODMgMjY3LjVMNjg4IDI2Ni41TDY5OC41IDI1OUw3MDQuNSAyNDlMNzA1LjUgMjQzTDcwNi41IDI0Mkw3MDYuNSAyMzhMNzA3LjUgMjM3TDcwNyAyMTYuNUw3MDUuNSAyMTlMNjk3IDIyNy41TDY4OCAyMzIuNUw2ODIgMjMzLjVMNjgxIDIzNC41TDY3NyAyMzQuNUw2NzYgMjM1LjVMNjY1IDIzNS41TDY2NCAyMzQuNUw2NTkgMjM0LjVMNjQ1IDIyOC41TDY0MyAyMjYuNUw2NDIgMjI2LjVMNjMyLjUgMjE3TDYzMi41IDIxNkw2MjkuNSAyMTNMNjI0LjUgMjAzTDYyNC41IDIwMUw2MjIuNSAxOTdMNjIyLjUgMTk0TDYyMS41IDE5M0w2MjEuNSAxODhMNjIwLjUgMTg3TDYyMC41IDE2OUw2MjEuNSAxNjhMNjIxLjUgMTYzTDYyMi41IDE2Mkw2MjMuNSAxNTVMNjI5LjUgMTQyTDYzMS41IDE0MEw2MzMuNSAxMzZMNjQzIDEyNi41TDY0NCAxMjYuNUw2NDkgMTIyLjVMNjUzIDEyMC41TDY2MSAxMTguNUw2NjIgMTE3LjVMNjY3IDExNy41Wk03ODUuNSAxMTdMNzk3IDExNi41TDc5OCAxMTcuNUw4MDMgMTE3LjVMODA0IDExOC41TDgxMCAxMTkuNUw4MTkgMTI0LjVMODI4LjUgMTM0TDgzMy41IDE0Mkw4MzMuNSAxNDRMODM1LjUgMTQ3TDgzNS41IDE0OUw4MzcuNSAxNTNMODM4LjUgMTYzTDgzOS41IDE2NEw4MzkuNSAxNzhMODM4IDE4MS41TDc1OCAxODEuNUw3NTcuNSAxOTBMNzU4LjUgMTkxTDc1OC41IDE5NUw3NTkuNSAxOTZMNzU5LjUgMTk4TDc2NS41IDIwOUw3NzAgMjEzLjVMNzcxIDIxMy41TDc3NiAyMTcuNUw3ODMgMjE5LjVMNzg0IDIyMC41TDc4NyAyMjAuNUw3ODggMjIxLjVMODEwIDIyMS41TDgxMSAyMjAuNUw4MTYgMjIwLjVMODE3IDIxOS41TDgyMCAyMTkuNUw4MjEgMjE4LjVMODI2IDIxNy41TDgyOSAyMTUuNUw4MjkuNSAyMTlMODMwLjUgMjIwTDgzMC41IDIyM0w4MzEuNSAyMjRMODMxLjUgMjI3TDgzMi41IDIyOEw4MzIuNSAyMzFMODMwIDIzMi41TDgyMiAyMzQuNUw4MjEgMjM1LjVMODE3IDIzNS41TDgxNiAyMzYuNUw4MTIgMjM2LjVMODExIDIzNy41TDgwMiAyMzcuNUw4MDEgMjM4LjVMNzg4IDIzOC41TDc4NyAyMzcuNUw3ODEgMjM3LjVMNzgwIDIzNi41TDc3NyAyMzYuNUw3NzYgMjM1LjVMNzcwIDIzNC41TDc1OSAyMjguNUw3NTAuNSAyMjFMNzUwLjUgMjIwTDc0Ni41IDIxNkw3NDUuNSAyMTNMNzQyLjUgMjA5TDc0Mi41IDIwN0w3NDAuNSAyMDRMNzQwLjUgMjAyTDczOC41IDE5OEw3MzguNSAxOTRMNzM3LjUgMTkzTDczNy41IDE4Nkw3MzYuNSAxODVMNzM2LjUgMTc0TDczNy41IDE3M0w3MzcuNSAxNjZMNzM4LjUgMTY1TDczOC41IDE2MUw3MzkuNSAxNjBMNzM5LjUgMTU3TDc0MC41IDE1Nkw3NDEuNSAxNTFMNzQ4LjUgMTM4TDc1My41IDEzM0w3NTMuNSAxMzJMNzYxIDEyNS41TDc3MCAxMjAuNUw3NzIgMTIwLjVMNzc5IDExNy41TDc4NSAxMTcuNVpNOTk1LjUgMTE3TDEwMDQgMTE2LjVMMTAwNi41IDExOEwxMDA2LjUgMTM3TDEwMDUgMTM3LjVMMTAwNCAxMzYuNUw5OTYgMTM2LjVMOTk1IDEzNy41TDk5MSAxMzcuNUw5ODUgMTQwLjVMOTc5LjUgMTQ1TDk3OS41IDE0Nkw5NzYuNSAxNDlMOTczLjUgMTU0TDk3My41IDE1Nkw5NzEuNSAxNjBMOTcxLjUgMTYzTDk3MC41IDE2NEw5NzAuNSAxNzBMOTY5LjUgMTcxTDk2OS41IDIzNUw5NDguNSAyMzVMOTQ4LjUgMTIwTDk2Ni41IDEyMEw5NjYuNSAxMzNMOTY3LjUgMTM0TDk2OCAxNDIuNUw5NjguNSAxNDBMOTczLjUgMTMxTDk4MiAxMjIuNUw5ODkgMTE4LjVMOTk1IDExNy41Wk0xMDQ5LjUgMTE3TDEwNjIgMTE2LjVMMTA2MyAxMTcuNUwxMDY4IDExNy41TDEwNjkgMTE4LjVMMTA3NCAxMTkuNUwxMDgyIDEyMy41TDEwODUgMTI2LjVMMTA4NiAxMjYuNUwxMDkzLjUgMTM1TDEwOTkuNSAxNDZMMTA5OS41IDE0OEwxMTAxLjUgMTUyTDExMDEuNSAxNTVMMTEwMi41IDE1NkwxMTAyLjUgMTYwTDExMDMuNSAxNjFMMTEwNCAxNjkuNUwxMTA2LjUgMTU2TDExMTEuNSAxNDRMMTExMy41IDE0MkwxMTE0LjUgMTM5TDExMTcuNSAxMzZMMTExNy41IDEzNUwxMTI5IDEyNC41TDExMzkgMTE5LjVMMTE0NSAxMTguNUwxMTQ2IDExNy41TDExNTEgMTE3LjVMMTE1MiAxMTYuNUwxMTY0IDExNi41TDExNjUgMTE3LjVMMTE3MCAxMTcuNUwxMTcxIDExOC41TDExNzQgMTE4LjVMMTE3NyAxMjAuNUwxMTgxIDEyMS41TDExODMgMTIzLjVMMTE4NyAxMjUuNUwxMTk0LjUgMTMzTDExOTQuNSAxMzRMMTE5OC41IDEzOUwxMjAxLjUgMTQ1TDEyMDEuNSAxNDdMMTIwNC41IDE1NEwxMjA0LjUgMTU4TDEyMDUuNSAxNTlMMTIwNS41IDE2N0wxMjA2LjUgMTY4TDEyMDYuNSAxNzVMMTIwNS41IDE3NkwxMjA1IDE4MS41TDExMjQgMTgxLjVMMTEyMy41IDE4NkwxMTI0LjUgMTg3TDExMjQuNSAxOTJMMTEyNS41IDE5M0wxMTI1LjUgMTk2TDExMjkuNSAyMDVMMTEzMS41IDIwN0wxMTMxLjUgMjA4TDExNDEgMjE2LjVMMTE0NyAyMTkuNUwxMTQ5IDIxOS41TDExNTAgMjIwLjVMMTE1NCAyMjAuNUwxMTU1IDIyMS41TDExNzcgMjIxLjVMMTE3OCAyMjAuNUwxMTgyIDIyMC41TDExODMgMjE5LjVMMTE5MCAyMTguNUwxMTkzIDIxNi41TDExOTYgMjE2LjVMMTE5OS41IDIzMUwxMTkxIDIzNC41TDExODggMjM0LjVMMTE4NyAyMzUuNUwxMTg0IDIzNS41TDExODMgMjM2LjVMMTE3OSAyMzYuNUwxMTc4IDIzNy41TDExNjkgMjM3LjVMMTE2OCAyMzguNUwxMTU1IDIzOC41TDExNTQgMjM3LjVMMTE0MyAyMzYuNUwxMTQyIDIzNS41TDExMzcgMjM0LjVMMTEyNyAyMjkuNUwxMTE1LjUgMjE5TDExMTUuNSAyMThMMTExMS41IDIxM0wxMTA1LjUgMTk5TDExMDUuNSAxOTVMMTEwNC41IDE5NEwxMTA0LjUgMTg5TDExMDMuNSAxODhMMTEwMyAxODEuNUwxMDIxLjUgMTgyTDEwMjEuNSAxODlMMTAyMi41IDE5MEwxMDIyLjUgMTk0TDEwMjMuNSAxOTVMMTAyNC41IDIwMEwxMDI4LjUgMjA3TDEwMzcgMjE1LjVMMTA0NSAyMTkuNUwxMDUxIDIyMC41TDEwNTIgMjIxLjVMMTA3NCAyMjEuNUwxMDc1IDIyMC41TDEwODAgMjIwLjVMMTA4MSAyMTkuNUwxMDg0IDIxOS41TDEwODUgMjE4LjVMMTA5MyAyMTYuNUwxMDk0LjUgMjE5TDEwOTQuNSAyMjJMMTA5NS41IDIyM0wxMDk1LjUgMjI2TDEwOTYuNSAyMjdMMTA5NiAyMzEuNUwxMDg5IDIzNC41TDEwODYgMjM0LjVMMTA4NSAyMzUuNUwxMDgyIDIzNS41TDEwODEgMjM2LjVMMTA3NiAyMzYuNUwxMDc1IDIzNy41TDEwNjcgMjM3LjVMMTA2NiAyMzguNUwxMDUzIDIzOC41TDEwNTIgMjM3LjVMMTA0NSAyMzcuNUwxMDQ0IDIzNi41TDEwNDEgMjM2LjVMMTA0MCAyMzUuNUwxMDMyIDIzMy41TDEwMjIgMjI3LjVMMTAxMi41IDIxOEwxMDEyLjUgMjE3TDEwMDguNSAyMTJMMTAwMy41IDIwMEwxMDAyLjUgMTkyTDEwMDEuNSAxOTFMMTAwMS41IDE2N0wxMDAyLjUgMTY2TDEwMDIuNSAxNjJMMTAwMy41IDE2MUwxMDAzLjUgMTU4TDEwMDQuNSAxNTdMMTAwNS41IDE1MkwxMDExLjUgMTQwTDEwMjQgMTI2LjVMMTAzNCAxMjAuNUwxMDM2IDEyMC41TDEwNDAgMTE4LjVMMTA0MyAxMTguNUwxMDQ0IDExNy41TDEwNDkgMTE3LjVaTTEzMjYuNSAxMTdMMTM0MCAxMTYuNUwxMzQxIDExNy41TDEzNDYgMTE3LjVMMTM0NyAxMTguNUwxMzUwIDExOC41TDEzNTEgMTE5LjVMMTM1NiAxMjAuNUwxMzY2LjUgMTI4TDEzNjYuNSAxMjlMMTM3MC41IDEzM0wxMzc0LjUgMTQxTDEzNzUuNSAxNDdMMTM3Ni41IDE0OEwxMzc2LjUgMTUyTDEzNzcuNSAxNTNMMTM3Ny41IDIxNEwxMzc4LjUgMjE1TDEzNzguNSAyMzBMMTM3OS41IDIzMUwxMzc5LjUgMjM1TDEzNjEgMjM1LjVMMTM2MC41IDIzMUwxMzU5LjUgMjMwTDEzNTkuNSAyMjJMMTM1OCAyMjEuNUwxMzU2LjUgMjI0TDEzNDggMjMxLjVMMTM0MCAyMzUuNUwxMzM4IDIzNS41TDEzMzQgMjM3LjVMMTMzMCAyMzcuNUwxMzI5IDIzOC41TDEzMTYgMjM4LjVMMTMxNSAyMzcuNUwxMzEyIDIzNy41TDEzMTEgMjM2LjVMMTMwNiAyMzUuNUwxMzAxIDIzMi41TDEyOTUuNSAyMjhMMTI5NS41IDIyN0wxMjkyLjUgMjI0TDEyODkuNSAyMTlMMTI4OS41IDIxN0wxMjg3LjUgMjEzTDEyODcuNSAxOTdMMTI4OC41IDE5NkwxMjg4LjUgMTkzTDEyOTMuNSAxODNMMTMwMiAxNzQuNUwxMzE1IDE2Ny41TDEzMTcgMTY3LjVMMTMyMSAxNjUuNUwxMzI0IDE2NS41TDEzMjUgMTY0LjVMMTMyOCAxNjQuNUwxMzI5IDE2My41TDEzNTYuNSAxNjFMMTM1Ni41IDE1MUwxMzU1LjUgMTUwTDEzNTUuNSAxNDdMMTM1MC41IDEzOUwxMzQ0IDEzNC41TDEzNDIgMTM0LjVMMTMzOCAxMzIuNUwxMzIyIDEzMi41TDEzMjEgMTMzLjVMMTMxNyAxMzMuNUwxMzE2IDEzNC41TDEzMDggMTM2LjVMMTMwNCAxMzguNUwxMzAyIDE0MC41TDEyOTkuNSAxNDBMMTI5OS41IDEzOEwxMjk4LjUgMTM3TDEyOTguNSAxMzVMMTI5NS41IDEyOEwxMjk2IDEyNi41TDEzMDMgMTIyLjVMMTMwNSAxMjIuNUwxMzExIDExOS41TDEzMTkgMTE4LjVMMTMyMCAxMTcuNUwxMzI2IDExNy41Wk0xMzkzLjUgMTIwTDE0MTUuNSAxMjBMMTQxNSAyMzUuNUwxMzkzLjUgMjM1TDEzOTMuNSAxMjFaTTc4Ni41IDEzMkw3OTMgMTMxLjVMNzk0IDEzMi41TDc5OCAxMzIuNUw4MDggMTM3LjVMODExLjUgMTQxTDgxNi41IDE1MEw4MTYuNSAxNTJMODE4LjUgMTU2TDgxOC41IDE2NEw4MTkuNSAxNjVMODE4IDE2Ni41TDc1OCAxNjYuNUw3NTcuNSAxNjNMNzU4LjUgMTYyTDc1OC41IDE1OUw3NTkuNSAxNThMNzYwLjUgMTUzTDc2NS41IDE0NEw3NzMgMTM2LjVMNzgyIDEzMi41TDc4NiAxMzIuNVpNMTA1MC41IDEzMkwxMDU3IDEzMS41TDEwNTggMTMyLjVMMTA2MiAxMzIuNUwxMDYzIDEzMy41TDEwNjUgMTMzLjVMMTA3MSAxMzYuNUwxMDc2LjUgMTQyTDEwODAuNSAxNDlMMTA4MC41IDE1MUwxMDgyLjUgMTU1TDEwODMuNSAxNjZMMTAyMiAxNjYuNUwxMDIxLjUgMTY0TDEwMjIuNSAxNjNMMTAyMi41IDE1OUwxMDIzLjUgMTU4TDEwMjMuNSAxNTZMMTAyNS41IDE1M0wxMDI2LjUgMTQ5TDEwMjguNSAxNDdMMTAzMC41IDE0M0wxMDM5IDEzNS41TDEwNDYgMTMyLjVMMTA1MCAxMzIuNVpNMTE1My41IDEzMkwxMTU5IDEzMS41TDExNjAgMTMyLjVMMTE2NSAxMzIuNUwxMTY2IDEzMy41TDExNjggMTMzLjVMMTE3MiAxMzUuNUwxMTc5LjUgMTQzTDExODIuNSAxNDhMMTE4Mi41IDE1MEwxMTg0LjUgMTU0TDExODQuNSAxNTdMMTE4NS41IDE1OEwxMTg1LjUgMTY2TDExMjQuNSAxNjZMMTEyNC41IDE2MUwxMTI1LjUgMTYwTDExMjYuNSAxNTRMMTEyOS41IDE0OEwxMTM1LjUgMTQxTDExMzUuNSAxNDBMMTE0NSAxMzMuNUwxMTQ3IDEzMy41TDExNDggMTMyLjVMMTE1MyAxMzIuNVpNNjY5LjUgMTM0TDY4MyAxMzMuNUw2ODQgMTM0LjVMNjkxIDEzNi41TDcwMS41IDE0Nkw3MDUuNSAxNTNMNzA1LjUgMTU1TDcwNi41IDE1Nkw3MDYuNSAxNjBMNzA3LjUgMTYxTDcwNy41IDE5MEw3MDYuNSAxOTFMNzA2LjUgMTk2TDcwNS41IDE5N0w3MDUuNSAxOTlMNjk4LjUgMjEwTDY5MyAyMTQuNUw2ODQgMjE4LjVMNjgwIDIxOC41TDY3OSAyMTkuNUw2NjcgMjE4LjVMNjU3IDIxMy41TDY0OS41IDIwNkw2NDQuNSAxOTZMNjQ0LjUgMTk0TDY0My41IDE5M0w2NDMuNSAxODlMNjQyLjUgMTg4TDY0Mi41IDE4MEw2NDEuNSAxNzlMNjQxLjUgMTc1TDY0Mi41IDE3NEw2NDIuNSAxNjZMNjQzLjUgMTY1TDY0My41IDE2MUw2NDQuNSAxNjBMNjQ1LjUgMTU1TDY1MS41IDE0NUw2NTcgMTM5LjVMNjY0IDEzNS41TDY2OSAxMzQuNVpNNDYxLjUgMTc3TDQ3Ny41IDE3N0w0NzcuNSAxOThMNDc2LjUgMTk5TDQ3NS41IDIwNUw0NzEuNSAyMTJMNDY3IDIxNi41TDQ1OCAyMjEuNUw0NTYgMjIxLjVMNDU1IDIyMi41TDQ0MiAyMjIuNUw0MzQgMjE4LjVMNDI4LjUgMjEwTDQyNy41IDIwMEw0MjguNSAxOTlMNDI4LjUgMTk1TDQzMC41IDE5MUw0MzggMTgzLjVMNDQ0IDE4MC41TDQ0NiAxODAuNUw0NTAgMTc4LjVMNDU0IDE3OC41TDQ1NSAxNzcuNUw0NjEgMTc3LjVaTTEzNDEuNSAxNzdMMTM1Ny41IDE3N0wxMzU3LjUgMjAwTDEzNTYuNSAyMDFMMTM1Ni41IDIwNEwxMzUyLjUgMjExTDEzNDMgMjE5LjVMMTMzNiAyMjEuNUwxMzM1IDIyMi41TDEzMjIgMjIyLjVMMTMyMSAyMjEuNUwxMzE5IDIyMS41TDEzMTcgMjE5LjVMMTMxNiAyMTkuNUwxMzA5LjUgMjEyTDEzMDkuNSAyMTBMMTMwOC41IDIwOUwxMzA4LjUgMTk3TDEzMTEuNSAxOTBMMTMxNyAxODQuNUwxMzIyIDE4MS41TDEzMjQgMTgxLjVMMTMyNyAxNzkuNUwxMzM0IDE3OC41TDEzMzUgMTc3LjVMMTM0MSAxNzcuNVpNMTIxOC41IDIwOUwxMjI4IDIwOC41TDEyMzIgMjEwLjVMMTIzNS41IDIxNEwxMjM3LjUgMjE4TDEyMzcuNSAyMjhMMTIzNC41IDIzNEwxMjMwIDIzNy41TDEyMjggMjM3LjVMMTIyNyAyMzguNUwxMjIwIDIzOC41TDEyMTkgMjM3LjVMMTIxNyAyMzcuNUwxMjEyLjUgMjM0TDEyMDkuNSAyMjhMMTIwOS41IDIxOEwxMjExLjUgMjE0TDEyMTUgMjEwLjVMMTIxOCAyMDkuNVpNMTU4Ni41IDIxNkwxNTg3LjUgMjE2TDE1ODcuNSAyMjJMMTU4Ni41IDIyMkwxNTg2LjUgMjE3WiI+PC9wYXRoPjwvc3ZnPg=="
LOGO_HTML = '<img src="data:image/svg+xml;base64,' + LOGO_B64 + '" style="width:100%;max-width:220px;display:block;margin-bottom:4px;">'

st.set_page_config(
    page_title="Reservation Agent | OrangeTree Global",
    page_icon="🌳",
    layout="wide",
)

st.markdown("""
<style>
    .section-header {
        border-left: 4px solid #F36621;
        padding: 0.3rem 0.8rem;
        background: #fff3ee;
        border-radius: 0 4px 4px 0;
        margin: 1.2rem 0 0.6rem 0;
        font-weight: 600;
    }
    .booking-card {
        background: #f0fff4;
        border: 2px solid #1A7A30;
        border-radius: 8px;
        padding: 1rem 1.2rem;
        margin-top: 1rem;
    }
    .booking-title {
        color: #1A7A30;
        font-size: 1.1rem;
        font-weight: 700;
        margin-bottom: 0.5rem;
    }
    .stChatMessage { border-radius: 8px; }
</style>
""", unsafe_allow_html=True)

st.markdown(
    f'<img src="data:image/svg+xml;base64,{LOGO_B64}" style="width:280px;max-width:100%;display:block;margin-bottom:12px;">',
    unsafe_allow_html=True
)
st.markdown("## AI Reservation Chat Agent")
st.markdown("A conversational booking agent for restaurants, clinics, salons and more — collects all booking details and confirms.")
st.divider()

with st.sidebar:
    st.markdown(LOGO_HTML, unsafe_allow_html=True)
    st.markdown("---")
    api_key = st.text_input("Anthropic API Key", type="password", help="Get from console.anthropic.com")
    model = st.selectbox("Model", ["claude-opus-4-8", "claude-sonnet-4-6", "claude-haiku-4-5-20251001"], index=2,
        help="Haiku is fast and responsive for chat")
    st.markdown("---")
    st.markdown("**Business Setup**")
    business_name = st.text_input("Business name", placeholder="Bhawanipur House")
    business_type = st.selectbox("Business type", [
        "Restaurant / Dining", "Cafe / Coffee Shop", "Clinic / Medical",
        "Salon / Spa", "Hotel / Guesthouse", "Fitness / Gym", "Other"
    ])
    opening_hours = st.text_input("Opening hours", placeholder="Mon-Sat 11am-10pm, Sun 12pm-9pm")
    capacity_note = st.text_input("Capacity / slots note", placeholder="Tables for 2-20 guests, last booking 9pm")
    special_notes = st.text_area("Special info for the agent", 
        placeholder="We do not accept reservations for fewer than 2 guests. Call +91 XXXXX for large parties (15+).",
        height=80)
    st.markdown("---")
    if st.button("Reset conversation", use_container_width=True):
        st.session_state["messages"] = []
        st.session_state["booking"] = {}
        st.rerun()
    st.info("UC10 of OrangeTree's AI SME Suite. Powered by Claude API.", icon="ℹ️")

if "messages" not in st.session_state:
    st.session_state["messages"] = []
if "booking" not in st.session_state:
    st.session_state["booking"] = {}

col_chat, col_booking = st.columns([2, 1], gap="large")

with col_chat:
    st.markdown('<div class="section-header">Customer Chat</div>', unsafe_allow_html=True)

    for msg in st.session_state["messages"]:
        with st.chat_message(msg["role"]):
            st.markdown(msg["content"])

    user_input = st.chat_input("Type your message...")

    if user_input:
        st.session_state["messages"].append({"role": "user", "content": user_input})

        if not api_key:
            st.error("Enter your Anthropic API key in the sidebar.")
        else:
            biz = business_name if business_name.strip() else "our venue"
            btype = business_type
            hours = opening_hours if opening_hours.strip() else "our standard hours"
            cap = capacity_note if capacity_note.strip() else ""
            notes = special_notes if special_notes.strip() else ""

            system = f"""You are the booking agent for {biz}, a {btype}.

Your job is to help customers make a reservation by collecting:
1. Date and time requested
2. Number of guests (or appointment type for clinics/salons)
3. Customer name
4. Contact number or email

Business hours: {hours}
{f"Capacity notes: {cap}" if cap else ""}
{f"Special notes: {notes}" if notes else ""}

Once you have all 4 details, confirm the booking clearly with a summary.
Be friendly, concise, and professional. If a requested slot seems outside hours or capacity, politely advise.

After you have collected all booking details, include this JSON block at the end of your response (hidden from customer):
BOOKING_DATA:{{"name":"...","date":"...","time":"...","guests":"...","contact":"...","confirmed":true}}

If you don't have all details yet, do not include the BOOKING_DATA block."""

            messages_for_api = []
            for m in st.session_state["messages"]:
                messages_for_api.append({"role": m["role"], "content": m["content"]})

            with st.spinner("Agent typing..."):
                client = anthropic.Anthropic(api_key=api_key)
                resp = client.messages.create(
                    model=model,
                    max_tokens=600,
                    system=system,
                    messages=messages_for_api
                )

            reply = resp.content[0].text

            # Extract booking data if present
            if "BOOKING_DATA:" in reply:
                parts = reply.split("BOOKING_DATA:")
                visible_reply = parts[0].strip()
                try:
                    booking_json = parts[1].strip()
                    st.session_state["booking"] = json.loads(booking_json)
                except Exception:
                    pass
            else:
                visible_reply = reply

            st.session_state["messages"].append({"role": "assistant", "content": visible_reply})
            st.rerun()

with col_booking:
    st.markdown('<div class="section-header">Booking Summary</div>', unsafe_allow_html=True)

    booking = st.session_state.get("booking", {})

    if booking.get("confirmed"):
        biz_display = business_name if business_name.strip() else "Venue"
        st.markdown(
            '<div class="booking-card">' +
            '<div class="booking-title">Booking Confirmed</div>' +
            f'<div><b>Venue:</b> {biz_display}</div>' +
            f'<div><b>Guest:</b> {booking.get("name", "—")}</div>' +
            f'<div><b>Date:</b> {booking.get("date", "—")}</div>' +
            f'<div><b>Time:</b> {booking.get("time", "—")}</div>' +
            f'<div><b>Guests:</b> {booking.get("guests", "—")}</div>' +
            f'<div><b>Contact:</b> {booking.get("contact", "—")}</div>' +
            '</div>',
            unsafe_allow_html=True
        )

        booking_text = f"""RESERVATION CONFIRMATION
========================
Venue: {biz_display}
Guest: {booking.get("name", "")}
Date: {booking.get("date", "")}
Time: {booking.get("time", "")}
Guests: {booking.get("guests", "")}
Contact: {booking.get("contact", "")}
Confirmed: {datetime.now().strftime("%d/%m/%Y %H:%M")}
"""
        st.download_button(
            "Download Confirmation",
            data=booking_text,
            file_name="reservation_confirmation.txt",
            mime="text/plain",
            use_container_width=True
        )
    else:
        st.markdown("**Pending details:**")
        fields = [
            ("Name", booking.get("name")),
            ("Date", booking.get("date")),
            ("Time", booking.get("time")),
            ("Guests", booking.get("guests")),
            ("Contact", booking.get("contact")),
        ]
        for label, val in fields:
            icon = "✓" if val else "○"
            st.markdown(f"{icon} **{label}:** {val if val else '_not yet collected_'}")

        if not st.session_state["messages"]:
            st.info("Start a conversation to begin the booking.", icon="ℹ️")

    st.markdown("---")
    st.markdown("**Conversation history**")
    st.caption(f"{len(st.session_state['messages'])} messages")

st.caption("OrangeTree Global | AI SME Suite — UC10: Reservation Chat Agent")
